namespace MPT.CSI.API.Core.Program.ModelBehavior.ObjectModel
{
    /// <summary>
    /// Object has edge constraints.
    /// </summary>
    public interface IEdgeConstraints
    {
        /// <summary>
        /// This function retrieves the generated edge constraint assignments to objects.
        /// </summary>
        /// <param name="name">The name of an existing object.</param>
        /// <param name="constraintExists">True: An automatic edge constraint is generated by the program for the object in the analysis model.</param>
        void GetEdgeConstraint(string name,
            ref bool constraintExists);

        /// <summary>
        /// This function makes generated edge constraint assignments to solid objects.
        /// </summary>
        /// <param name="name">The name of an existing solid object or group, depending on the value of the <paramref name="itemType"/> item.</param>
        /// <param name="constraintExists">True: An automatic edge constraint is generated by the program for the object in the analysis model.</param>
        /// <param name="itemType">If this item is <see cref="eItemType.Object"/>, the assignments are retrieved for the objects specified by the <paramref name="name"/> item.
        /// If this item is <see cref="eItemType.Group"/>, the assignments are retrieved for the objects included in the group specified by the <paramref name="name"/> item.
        /// If this item is <see cref="eItemType.SelectedObjects"/>, the assignments are retrieved for all selected objects, and the <paramref name="name"/> item is ignored.</param>
        void SetEdgeConstraint(string name,
            bool constraintExists,
            eItemType itemType = eItemType.Object);
    }
}